import {
  BUILTIN_ARCHITECTURE_AND_CODE_ORGANIZATION_INSTRUCTIONS,
  BUILTIN_DESTRUCTIVE_OPERATION_GUARD_INSTRUCTIONS,
  BUILTIN_FRONTEND_OUTPUT_PURITY_INSTRUCTIONS,
  BUILTIN_GIT_COMMIT_SUMMARY_INSTRUCTIONS,
  BUILTIN_LOW_OVERHEAD_WORKFLOW_INSTRUCTIONS,
  BUILTIN_PAYLOAD_GUARD_INSTRUCTIONS,
  BUILTIN_PLAN_LITE_INSTRUCTIONS,
  BUILTIN_REQUIREMENT_BOUNDARY_AND_MODULARITY_INSTRUCTIONS,
  BUILTIN_THREAD_HANDOFF_SWITCH_INSTRUCTIONS,
  BUILTIN_WRITE_POLICY_INSTRUCTIONS,
} from "./builtin-instructions.js";
export function buildServerInstructions(): string {
  return [
    "VectorMind MCP is available in this session. Use it to avoid guessing project context.",
    "Development guideline scope: VectorMind instructions define development conventions, project-memory conventions, code-organization conventions, and delivery-quality expectations.",
    "Project root resolution order: tool argument project_root (recommended for clients without roots/list), then VECTORMIND_ROOT (avoid hardcoding in global config), then MCP roots/list (best-effort; falls back quickly if unsupported), then process.cwd() (so start your MCP client in the project directory for per-project isolation).",
    "If root_source is fallback, file watching/indexing is disabled (pass project_root to enable per-project tracking).",
    "",
    "Built-in write-operation quality policy:",
    BUILTIN_WRITE_POLICY_INSTRUCTIONS,
    "",
    "Built-in task-list / Plan-Lite quality policy:",
    BUILTIN_PLAN_LITE_INSTRUCTIONS,
    "",
    "Built-in destructive-operation quality guard:",
    BUILTIN_DESTRUCTIVE_OPERATION_GUARD_INSTRUCTIONS,
    "",
    "Built-in architecture and code-organization quality policy:",
    BUILTIN_ARCHITECTURE_AND_CODE_ORGANIZATION_INSTRUCTIONS,
    "",
    "Built-in requirement boundary and modularity quality policy:",
    BUILTIN_REQUIREMENT_BOUNDARY_AND_MODULARITY_INSTRUCTIONS,
    "",
    "Built-in frontend output-purity quality policy:",
    BUILTIN_FRONTEND_OUTPUT_PURITY_INSTRUCTIONS,
    "",
    "Built-in git commit summary quality policy:",
    BUILTIN_GIT_COMMIT_SUMMARY_INSTRUCTIONS,
    "",
    "Built-in low-overhead execution and heavy-thread quality policy:",
    BUILTIN_LOW_OVERHEAD_WORKFLOW_INSTRUCTIONS,
    "",
    "Built-in payload / oversized-thread quality guard:",
    BUILTIN_PAYLOAD_GUARD_INSTRUCTIONS,
    "",
    "Built-in thread handoff / switch-gate quality policy:",
    BUILTIN_THREAD_HANDOFF_SWITCH_INSTRUCTIONS,
    "",
    "Required VectorMind call chain for development work:",
    "- Start/resume: call bootstrap_context with project_root and a short query unless the task is purely execution-first and all targets are already known.",
    "- Before edits: call start_requirement for the current user request, then call preflight_change_scope with the planned files/modules before changing files.",
    "- During edits: if preflight_change_scope says safe_to_edit=false, narrow the plan first. If it returns huge_file_modularization_required, use plan_large_file_split, mechanical_modularization, and record_large_file_split before normal feature work.",
    "- After edits: call get_pending_changes, then sync_change_intent with what changed and why.",
    "- Newer decision wins: when the user changes/reverses a rule, call upsert_decision and supersede_memory/upsert_decision supersedes fields so old memories do not override the current rule.",
    "- Milestone/end: update project summary or add durable notes/conventions, and complete_requirement when the requirement is done.",
    "",
    "VectorMind workflow:",
    "- Tool outputs are compact by default. Pass format=json only when you need full structured data.",
    "- On every new conversation/session for analysis/design/development work: call bootstrap_context({ query: <current goal> }) first (or at least get_brain_dump()) to restore compact context and retrieve relevant matches from the local memory store (FTS/token/LIKE).",
    "  - Output is compact by default. Use include_content=true only when you truly need full text (it increases tokens).",
    "  - bootstrap_context/get_brain_dump always include a small recency anchor named current_context (latest active requirements, recent notes, and recent change intents) in addition to query matches; tune output size with: requirements_limit/changes_limit/notes_limit/decisions_limit/current_context_limit, preview_chars, pending_limit/pending_offset.",
    "  - Prefer read_memory_item(id, offset, limit) to fetch full text on demand instead of returning large content in other tool outputs.",
    "- For pure execution-first tasks with explicit targets (for example compile/build/run/launch/package/publish/test rerun), you may skip retrieval and go straight to the minimum necessary shell or host tools unless code/context lookup is actually needed to unblock execution.",
    "- If rtk is installed or VectorMind's bundled RTK shim is verified (detect_rtk with gain_ok=true), prefix shell commands with the command returned by detect_rtk. Usually this is rtk (rtk git status, rtk npm run build, rtk rg ...); in npx/MCP-only installs it may be a package shim command such as node <...>/rtk-shim.js.",
    "- If rtk is missing and the user asks to install it, use install_rtk first with dry_run=true to show the exact commands; execute with dry_run=false only when the user explicitly asks to install/init.",
    "- To read local Codex skill/prompt/rule files (for example SKILL.md under CODEX_HOME or AGENTS_HOME), prefer read_codex_text_file({ path }) instead of assuming another local-file MCP resource server exists.",
    "- For project file/directory browsing, prefer list_project_files({ path, recursive?, max_depth? }) over shelling out to Get-ChildItem/ls. It respects ignore rules and keeps output bounded.",
    "- For small/medium raw file reads, prefer read_file_text({ path, offset?, max_chars? }) over Get-Content -Raw. Use read_file_lines(...) when you need deterministic line ranges or the file may be large.",
    "- For raw repo text search with exact file+line+col matches, prefer grep({ query: <pattern> }). It uses ripgrep against real project files when available, applies built-in noise filters, and only falls back to indexed search if ripgrep is unavailable.",
    "- To read a bounded segment of a file, prefer read_file_lines({ path: <file>, from_line/to_line or total_count }) over unbounded file reads.",
    "- BEFORE editing code: call start_requirement(title, background) to set the active requirement.",
    "  - When the user names a narrow feature/domain, pass scope_allow/allowed_paths and scope_deny/denied_paths when useful. These are generic project-specific scope boundaries, not business-specific built-ins.",
    "- BEFORE editing once target files/modules are known: call preflight_change_scope(intent, files/planned_files, optional scope_allow/scope_deny/allowed_paths/denied_paths). If ok=false/safe_to_edit=false or it returns development_warnings, stop before editing and narrow the plan unless the user explicitly expands the requirement.",
    "- Treat the active requirement as the only change boundary. Do not add extra business behavior, new flows, new fields, new interfaces, or touch completed/related features unless the user explicitly asked or the change is strictly necessary.",
    "- Do not keep piling new feature code into a large single file. Prefer small modules/services/components; if an implementation file is already large, split it before adding more responsibilities.",
    "- If preflight_change_scope/read_file_lines/grep/query_codebase/get_pending_changes/sync_change_intent returns huge_file_modularization_required, do not continue normal feature work. Call plan_large_file_split, perform mechanical modularization with real module names/directories, never create generated/parts/partN files, then call record_large_file_split before resuming normal feature work. Only use preflight_change_scope(change_mode='mechanical_modularization') for the split itself; use change_mode='emergency_hotfix' only for the smallest urgent fix and still record why the split was deferred.",
    "- AFTER editing + saving: call get_pending_changes() to see unsynced files, then call sync_change_intent(intent, files). (You can omit files to auto-link all pending changes.)",
    "- If preflight_change_scope, read_file_lines, grep, query_codebase, get_pending_changes, or sync_change_intent returns development_warnings, address those warnings before continuing or explain why the current requirement truly needs that scope.",
    "- After major milestones/decisions: call upsert_project_summary(summary) and/or add_note(...) to persist durable context locally.",
    "- When a requirement or user decision changes/reverses an older behavior, call upsert_decision(key, title, content, supersedes_req_ids?/supersedes_memory_ids?) and/or supersede_memory(...). Current decisions are shown in bootstrap_context/get_brain_dump and superseded memories are hidden from default semantic recall so stale requirements do not override newer facts.",
    "- If the user states a durable project convention (build commands, frameworks, naming rules, output paths): call upsert_convention(key, content, tags) so it is applied in future sessions.",
    "- When you need full text for a specific note/summary/match: call read_memory_item(id, offset, limit) and page through it.",
    "- When asked to locate code (class/function/type): call query_codebase(query) instead of guessing.",
    "- When you need to recall relevant context from history/code/docs: call semantic_search(query, ...) instead of guessing. It uses local FTS/token/LIKE recall so recent explicit wording and durable decisions stay visible without remote model loading.",
    "- VectorMind automatically runs small, throttled memory maintenance to compact old completed history and prune stale indexes in long-lived projects. For large repos that feel slow, call maintain_memory({ dry_run: true }) first, then maintain_memory({ dry_run: false }) if the plan looks correct.",
    "- Use get_token_savings({ format: 'compact' }) when you need to verify how many tokens VectorMind compact outputs saved.",
    "",
    "If tool output conflicts with assumptions, trust the tool output.",
  ].join("\n");
}
